// Generated by scripts/optimize-mat-cutouts.mjs — do not edit by hand.
//
// The ten mat cutouts, each composed on the same 4:5 transparent frame at three
// widths. `srcSet` is consumed by `MatPlate`, which renders a plain <img> —
// `next/image`'s custom loader has no resizer in front of `public/`, so native
// srcset is the only path here that actually serves a smaller file.

export type MatCutout = {
  name: string;
  src: string;
  srcSet: string;
  width: number;
  height: number;
  alt: string;
};

export const MAT_CUTOUTS = {
  'tan-diamond': {
    name: 'Tan diamond weave',
    src: '/products/mat-01-tan-diamond-960.webp',
    srcSet: '/products/mat-01-tan-diamond-480.webp 480w, /products/mat-01-tan-diamond-720.webp 720w, /products/mat-01-tan-diamond-960.webp 960w',
    width: 960,
    height: 1200,
    alt: 'Tan diamond weave Motormats car mat, photographed flat',
  },
  'blue-plaid': {
    name: 'Cobalt plaid',
    src: '/products/mat-02-blue-plaid-960.webp',
    srcSet: '/products/mat-02-blue-plaid-480.webp 480w, /products/mat-02-blue-plaid-720.webp 720w, /products/mat-02-blue-plaid-960.webp 960w',
    width: 960,
    height: 1200,
    alt: 'Cobalt plaid Motormats car mat, photographed flat',
  },
  'graphite-rib': {
    name: 'Graphite centre rib',
    src: '/products/mat-03-graphite-rib-960.webp',
    srcSet: '/products/mat-03-graphite-rib-480.webp 480w, /products/mat-03-graphite-rib-720.webp 720w, /products/mat-03-graphite-rib-960.webp 960w',
    width: 960,
    height: 1200,
    alt: 'Graphite centre rib Motormats car mat, photographed flat',
  },
  'camel-rib': {
    name: 'Camel tonal rib',
    src: '/products/mat-04-camel-rib-960.webp',
    srcSet: '/products/mat-04-camel-rib-480.webp 480w, /products/mat-04-camel-rib-720.webp 720w, /products/mat-04-camel-rib-960.webp 960w',
    width: 960,
    height: 1200,
    alt: 'Camel tonal rib Motormats car mat, photographed flat',
  },
  'ash-check': {
    name: 'Ash check',
    src: '/products/mat-05-ash-check-960.webp',
    srcSet: '/products/mat-05-ash-check-480.webp 480w, /products/mat-05-ash-check-720.webp 720w, /products/mat-05-ash-check-960.webp 960w',
    width: 960,
    height: 1200,
    alt: 'Ash check Motormats car mat, photographed flat',
  },
  'onyx-honeycomb': {
    name: 'Onyx honeycomb',
    src: '/products/mat-06-onyx-honeycomb-960.webp',
    srcSet: '/products/mat-06-onyx-honeycomb-480.webp 480w, /products/mat-06-onyx-honeycomb-720.webp 720w, /products/mat-06-onyx-honeycomb-960.webp 960w',
    width: 960,
    height: 1200,
    alt: 'Onyx honeycomb Motormats car mat, photographed flat',
  },
  'silver-plush': {
    name: 'Silver plush',
    src: '/products/mat-07-silver-plush-960.webp',
    srcSet: '/products/mat-07-silver-plush-480.webp 480w, /products/mat-07-silver-plush-720.webp 720w, /products/mat-07-silver-plush-960.webp 960w',
    width: 960,
    height: 1200,
    alt: 'Silver plush Motormats car mat, photographed flat',
  },
  'cobalt-stripe': {
    name: 'Cobalt stripe',
    src: '/products/mat-08-cobalt-stripe-960.webp',
    srcSet: '/products/mat-08-cobalt-stripe-480.webp 480w, /products/mat-08-cobalt-stripe-720.webp 720w, /products/mat-08-cobalt-stripe-960.webp 960w',
    width: 960,
    height: 1200,
    alt: 'Cobalt stripe Motormats car mat, photographed flat',
  },
  'walnut-stripe': {
    name: 'Walnut stripe',
    src: '/products/mat-09-walnut-stripe-960.webp',
    srcSet: '/products/mat-09-walnut-stripe-480.webp 480w, /products/mat-09-walnut-stripe-720.webp 720w, /products/mat-09-walnut-stripe-960.webp 960w',
    width: 960,
    height: 1200,
    alt: 'Walnut stripe Motormats car mat, photographed flat',
  },
  'crimson-stripe': {
    name: 'Crimson stripe',
    src: '/products/mat-10-crimson-stripe-960.webp',
    srcSet: '/products/mat-10-crimson-stripe-480.webp 480w, /products/mat-10-crimson-stripe-720.webp 720w, /products/mat-10-crimson-stripe-960.webp 960w',
    width: 960,
    height: 1200,
    alt: 'Crimson stripe Motormats car mat, photographed flat',
  },
} as const satisfies Record<string, MatCutout>;

export type MatCutoutSlug = keyof typeof MAT_CUTOUTS;

const BY_SRC: Record<string, MatCutout> = {
  ...Object.fromEntries(Object.values(MAT_CUTOUTS).map((cutout) => [cutout.src, cutout])),

  // The ids the seeded catalogue rows already hold. Mapping them here rather
  // than rewriting the rows keeps the database out of this entirely: dev and
  // production are the same MySQL instance, so a repoint would take effect for
  // live traffic the moment it ran, pointing at files that only exist after the
  // next deploy. These four files still exist and are now optimised too.
  '/products/1.webp': MAT_CUTOUTS['tan-diamond'],
  '/products/2.webp': MAT_CUTOUTS['blue-plaid'],
  '/products/3.webp': MAT_CUTOUTS['graphite-rib'],
  '/products/4.webp': MAT_CUTOUTS['camel-rib'],
};

/**
 * The cutout a stored assetId refers to, or null for anything else.
 *
 * A product row holds one asset id, but these plates ship at three widths. The
 * card looks the id up here to recover the full srcSet; a Cloudinary id, or any
 * other local file, misses and falls back to next/image.
 */
export function matCutoutForAsset(assetId: string | null | undefined): MatCutout | null {
  if (!assetId) return null;
  return BY_SRC[assetId] ?? null;
}
