// Generated by scripts/build-hero-slides.mjs — do not edit by hand.
//
// Two cuts per frame: a 16:9 landscape for the desktop band and a 9:16 portrait
// for a phone. The cover picks between them with <picture>, so each viewport
// gets a frame shaped like the space it has to fill and nothing is letterboxed.
//
// To add a frame, drop masters into motormats/hero-masters/ and rerun the script.

export type HeroCut = {
  src: string;
  srcSet: string;
  width: number;
  height: number;
};

export type HeroSlide = {
  slug: string;
  wide: HeroCut;
  tall: HeroCut;
  alt: string;
};

export const HERO_SLIDES: HeroSlide[] = [
  {
    slug: 'dune-toss',
    wide: { src: '/photos/hero/dune-toss-wide-2560.webp', srcSet: '/photos/hero/dune-toss-wide-1280.webp 1280w, /photos/hero/dune-toss-wide-1920.webp 1920w, /photos/hero/dune-toss-wide-2560.webp 2560w', width: 2560, height: 1440 },
    tall: { src: '/photos/hero/dune-toss-tall-1080.webp', srcSet: '/photos/hero/dune-toss-tall-640.webp 640w, /photos/hero/dune-toss-tall-828.webp 828w, /photos/hero/dune-toss-tall-1080.webp 1080w', width: 1080, height: 1920 },
    alt: 'A man on a desert dune with a full set of Motormats thrown into the air above him',
  },
  {
    slug: 'desert-run',
    wide: { src: '/photos/hero/desert-run-wide-2560.webp', srcSet: '/photos/hero/desert-run-wide-1280.webp 1280w, /photos/hero/desert-run-wide-1920.webp 1920w, /photos/hero/desert-run-wide-2560.webp 2560w', width: 2560, height: 1440 },
    tall: { src: '/photos/hero/desert-run-tall-1080.webp', srcSet: '/photos/hero/desert-run-tall-640.webp 640w, /photos/hero/desert-run-tall-828.webp 828w, /photos/hero/desert-run-tall-1080.webp 1080w', width: 1080, height: 1920 },
    alt: 'An SUV on desert sand, photographed head on from low down',
  },
  {
    slug: 'sand-drift',
    wide: { src: '/photos/hero/sand-drift-wide-2560.webp', srcSet: '/photos/hero/sand-drift-wide-1280.webp 1280w, /photos/hero/sand-drift-wide-1920.webp 1920w, /photos/hero/sand-drift-wide-2560.webp 2560w', width: 2560, height: 1440 },
    tall: { src: '/photos/hero/sand-drift-tall-1080.webp', srcSet: '/photos/hero/sand-drift-tall-640.webp 640w, /photos/hero/sand-drift-tall-828.webp 828w, /photos/hero/sand-drift-tall-1080.webp 1080w', width: 1080, height: 1920 },
    alt: 'Two Motormats laid on a dune as a wheel throws sand across them',
  },
  {
    slug: 'ambassador-door',
    wide: { src: '/photos/hero/ambassador-door-wide-2560.webp', srcSet: '/photos/hero/ambassador-door-wide-1280.webp 1280w, /photos/hero/ambassador-door-wide-1920.webp 1920w, /photos/hero/ambassador-door-wide-2560.webp 2560w', width: 2560, height: 1440 },
    tall: { src: '/photos/hero/ambassador-door-tall-1080.webp', srcSet: '/photos/hero/ambassador-door-tall-640.webp 640w, /photos/hero/ambassador-door-tall-828.webp 828w, /photos/hero/ambassador-door-tall-1080.webp 1080w', width: 1080, height: 1920 },
    alt: 'A man leaning against a vintage green Ambassador, a cream Motormats set draped over the open door',
  },
  {
    slug: 'jaipur-railing',
    wide: { src: '/photos/hero/jaipur-railing-wide-2560.webp', srcSet: '/photos/hero/jaipur-railing-wide-1280.webp 1280w, /photos/hero/jaipur-railing-wide-1920.webp 1920w, /photos/hero/jaipur-railing-wide-2560.webp 2560w', width: 2560, height: 1440 },
    tall: { src: '/photos/hero/jaipur-railing-tall-1080.webp', srcSet: '/photos/hero/jaipur-railing-tall-640.webp 640w, /photos/hero/jaipur-railing-tall-828.webp 828w, /photos/hero/jaipur-railing-tall-1080.webp 1080w', width: 1080, height: 1920 },
    alt: 'A tan woven Motormats mat held against a green railing in front of pink Jaipur sandstone',
  },
];
