// Generated by scripts/build-photo-grid.mjs — do not edit by hand.
//
// Grid-sized cuts of /public/photos, keyed by the frame's own name. Consumed by
// PhotoPlate, which renders a plain <img srcSet> — the custom image loader has
// no resizer, so native srcSet is the only thing that serves a smaller file.
//
// Alt text is not here: it belongs with the frame in photo-assets.ts.

export type PhotoCut = {
  src: string;
  srcSet: string;
  width: number;
  height: number;
};

export const PHOTO_GRID: Record<string, PhotoCut | undefined> = {
  'cover-tunnel': { src: '/photos/grid/cover-tunnel-900.webp', srcSet: '/photos/grid/cover-tunnel-400.webp 400w, /photos/grid/cover-tunnel-640.webp 640w, /photos/grid/cover-tunnel-900.webp 900w', width: 900, height: 1350 },
  'detail-badge': { src: '/photos/grid/detail-badge-900.webp', srcSet: '/photos/grid/detail-badge-400.webp 400w, /photos/grid/detail-badge-640.webp 640w, /photos/grid/detail-badge-900.webp 900w', width: 900, height: 1350 },
  'detail-crest': { src: '/photos/grid/detail-crest-900.webp', srcSet: '/photos/grid/detail-crest-400.webp 400w, /photos/grid/detail-crest-640.webp 640w, /photos/grid/detail-crest-900.webp 900w', width: 900, height: 1350 },
  'detail-radial': { src: '/photos/grid/detail-radial-900.webp', srcSet: '/photos/grid/detail-radial-400.webp 400w, /photos/grid/detail-radial-640.webp 640w, /photos/grid/detail-radial-900.webp 900w', width: 900, height: 1350 },
  'detail-stack': { src: '/photos/grid/detail-stack-900.webp', srcSet: '/photos/grid/detail-stack-400.webp 400w, /photos/grid/detail-stack-640.webp 640w, /photos/grid/detail-stack-900.webp 900w', width: 900, height: 1350 },
  'detail-weave': { src: '/photos/grid/detail-weave-900.webp', srcSet: '/photos/grid/detail-weave-400.webp 400w, /photos/grid/detail-weave-640.webp 640w, /photos/grid/detail-weave-900.webp 900w', width: 900, height: 1350 },
  'essay-cabin': { src: '/photos/grid/essay-cabin-900.webp', srcSet: '/photos/grid/essay-cabin-400.webp 400w, /photos/grid/essay-cabin-640.webp 640w, /photos/grid/essay-cabin-900.webp 900w', width: 900, height: 1350 },
  'essay-door': { src: '/photos/grid/essay-door-900.webp', srcSet: '/photos/grid/essay-door-400.webp 400w, /photos/grid/essay-door-640.webp 640w, /photos/grid/essay-door-900.webp 900w', width: 900, height: 1350 },
  'essay-headlight': { src: '/photos/grid/essay-headlight-900.webp', srcSet: '/photos/grid/essay-headlight-400.webp 400w, /photos/grid/essay-headlight-640.webp 640w, /photos/grid/essay-headlight-900.webp 900w', width: 900, height: 1350 },
  'essay-logo': { src: '/photos/grid/essay-logo-900.webp', srcSet: '/photos/grid/essay-logo-400.webp 400w, /photos/grid/essay-logo-640.webp 640w, /photos/grid/essay-logo-900.webp 900w', width: 900, height: 1350 },
  'essay-railing': { src: '/photos/grid/essay-railing-900.webp', srcSet: '/photos/grid/essay-railing-400.webp 400w, /photos/grid/essay-railing-640.webp 640w, /photos/grid/essay-railing-900.webp 900w', width: 900, height: 1350 },
  'essay-statue': { src: '/photos/grid/essay-statue-900.webp', srcSet: '/photos/grid/essay-statue-400.webp 400w, /photos/grid/essay-statue-640.webp 640w, /photos/grid/essay-statue-900.webp 900w', width: 900, height: 1350 },
  'gallery-heritage': { src: '/photos/grid/gallery-heritage-900.webp', srcSet: '/photos/grid/gallery-heritage-400.webp 400w, /photos/grid/gallery-heritage-640.webp 640w, /photos/grid/gallery-heritage-900.webp 900w', width: 900, height: 1350 },
  'gallery-sandstone': { src: '/photos/grid/gallery-sandstone-900.webp', srcSet: '/photos/grid/gallery-sandstone-400.webp 400w, /photos/grid/gallery-sandstone-640.webp 640w, /photos/grid/gallery-sandstone-900.webp 900w', width: 900, height: 1350 },
  'gallery-vintage': { src: '/photos/grid/gallery-vintage-900.webp', srcSet: '/photos/grid/gallery-vintage-400.webp 400w, /photos/grid/gallery-vintage-640.webp 640w, /photos/grid/gallery-vintage-900.webp 900w', width: 900, height: 1350 },
  'interior-driver': { src: '/photos/grid/interior-driver-900.webp', srcSet: '/photos/grid/interior-driver-400.webp 400w, /photos/grid/interior-driver-640.webp 640w, /photos/grid/interior-driver-900.webp 900w', width: 900, height: 1350 },
  'interior-wide': { src: '/photos/grid/interior-wide-900.webp', srcSet: '/photos/grid/interior-wide-400.webp 400w, /photos/grid/interior-wide-640.webp 640w, /photos/grid/interior-wide-900.webp 900w', width: 900, height: 1350 },
  'lifestyle-group': { src: '/photos/grid/lifestyle-group-900.webp', srcSet: '/photos/grid/lifestyle-group-400.webp 400w, /photos/grid/lifestyle-group-640.webp 640w, /photos/grid/lifestyle-group-900.webp 900w', width: 900, height: 1350 },
  'lifestyle-table': { src: '/photos/grid/lifestyle-table-900.webp', srcSet: '/photos/grid/lifestyle-table-400.webp 400w, /photos/grid/lifestyle-table-640.webp 640w, /photos/grid/lifestyle-table-900.webp 900w', width: 900, height: 1350 },
  'order-stack': { src: '/photos/grid/order-stack-900.webp', srcSet: '/photos/grid/order-stack-400.webp 400w, /photos/grid/order-stack-640.webp 640w, /photos/grid/order-stack-900.webp 900w', width: 900, height: 1350 },
  'order-trolley': { src: '/photos/grid/order-trolley-900.webp', srcSet: '/photos/grid/order-trolley-400.webp 400w, /photos/grid/order-trolley-640.webp 640w, /photos/grid/order-trolley-900.webp 900w', width: 900, height: 1350 },
  'range-7d': { src: '/photos/grid/range-7d-900.webp', srcSet: '/photos/grid/range-7d-400.webp 400w, /photos/grid/range-7d-640.webp 640w, /photos/grid/range-7d-900.webp 900w', width: 900, height: 1350 },
  'range-carbon': { src: '/photos/grid/range-carbon-900.webp', srcSet: '/photos/grid/range-carbon-400.webp 400w, /photos/grid/range-carbon-640.webp 640w, /photos/grid/range-carbon-900.webp 900w', width: 900, height: 1350 },
  'range-carpet': { src: '/photos/grid/range-carpet-900.webp', srcSet: '/photos/grid/range-carpet-400.webp 400w, /photos/grid/range-carpet-640.webp 640w, /photos/grid/range-carpet-900.webp 900w', width: 900, height: 1350 },
  'range-weather': { src: '/photos/grid/range-weather-900.webp', srcSet: '/photos/grid/range-weather-400.webp 400w, /photos/grid/range-weather-640.webp 640w, /photos/grid/range-weather-900.webp 900w', width: 900, height: 1350 },
  'story-carbon': { src: '/photos/grid/story-carbon-900.webp', srcSet: '/photos/grid/story-carbon-400.webp 400w, /photos/grid/story-carbon-640.webp 640w, /photos/grid/story-carbon-900.webp 900w', width: 900, height: 1350 },
  'story-luxury': { src: '/photos/grid/story-luxury-900.webp', srcSet: '/photos/grid/story-luxury-400.webp 400w, /photos/grid/story-luxury-640.webp 640w, /photos/grid/story-luxury-900.webp 900w', width: 900, height: 1350 },
  'story-monsoon': { src: '/photos/grid/story-monsoon-900.webp', srcSet: '/photos/grid/story-monsoon-400.webp 400w, /photos/grid/story-monsoon-640.webp 640w, /photos/grid/story-monsoon-900.webp 900w', width: 900, height: 1350 },
  'zone-fit': { src: '/photos/grid/zone-fit-900.webp', srcSet: '/photos/grid/zone-fit-400.webp 400w, /photos/grid/zone-fit-640.webp 640w, /photos/grid/zone-fit-900.webp 900w', width: 900, height: 1350 },
  'zone-weather': { src: '/photos/grid/zone-weather-900.webp', srcSet: '/photos/grid/zone-weather-400.webp 400w, /photos/grid/zone-weather-640.webp 640w, /photos/grid/zone-weather-900.webp 900w', width: 900, height: 1350 },
};

/** The grid cut for a `/photos/<name>.webp` source, if one was generated. */
export function photoCutFor(src: string): PhotoCut | undefined {
  const name = src.replace(/^.*\//, '').replace(/\.webp$/, '');
  return PHOTO_GRID[name];
}
