// Generated by scripts/build-process-steps.mjs — do not edit by hand.
//
// Geometry only. What each illustration depicts, and the copy beside it, are
// editorial and live in the section that renders them.

export type ProcessArt = {
  src: string;
  width: number;
  height: number;
};

export const PROCESS_ART: ProcessArt[] = [
  { src: '/process/step-1.webp', width: 390, height: 455 },
  { src: '/process/step-2.webp', width: 398, height: 455 },
  { src: '/process/step-3.webp', width: 395, height: 455 },
  { src: '/process/step-4.webp', width: 398, height: 455 },
  { src: '/process/step-5.webp', width: 393, height: 455 },
];
